services:
    organizr:
        volumes:
            - /srv/containers/organizr/config:/config
        #ports:
        #    - 80:80
        image: organizr/organizr
        deploy:
          placement:
            constraints: [node.role == manager]
          labels:
            - "traefik.enable=true"
            - "traefik.http.routers.organizr.rule=Host(\"${FQDN}\")" #Define in Portainer
            - "traefik.http.routers.organizr.entrypoints=websecure"
            - "traefik.http.services.organizr.loadbalancer.server.port=80"
            - "traefik.http.routers.organizr.service=organizr"
            - "traefik.http.routers.organizr.tls.certresolver=cloudflare"
        networks:
          - traefik_public
networks:
  traefik_public:
    external: true
