services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    #ports:
    #  - '8080:8080'
    volumes:
      - /srv/containers/stirling-pdf/trainingData:/usr/share/tessdata #Required for extra OCR languages
      - /srv/containers/stirling-pdf/extraConfigs:/configs
#      - ./customFiles:/customFiles/
#      - ./logs:/logs/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=en_GB
    networks:
      - traefik_public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        # Frontend
        - "traefik.enable=true"
        - "traefik.http.routers.stirling-pdf.rule=Host(\"${FQDN}\")" #Define in portainer
        - "traefik.http.routers.stirling-pdf.entrypoints=websecure"
        - "traefik.http.services.stirling-pdf.loadbalancer.server.port=8080"
        - "traefik.http.routers.stirling-pdf.service=stirling-pdf"
        - "traefik.http.routers.stirling-pdf.tls.certresolver=cloudflare"
networks:
  traefik_public:
    driver: overlay
    name: traefik_public
    attachable: true