services:
  statping-ng:
    image: adamboutcher/statping-ng:latest
    volumes:
      - /srv/containers/statping:/app
    environment:
      DB_CONN: sqlite
    #ports:
    #  - 8080:8080
    deploy:
        placement:
          constraints: [node.role == manager]
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.statping.rule=Host(\"${FQDN}\")" #Define in POrtainer
          - "traefik.http.routers.statping.entrypoints=websecure"
          - "traefik.http.services.statping.loadbalancer.server.port=8080"
          - "traefik.http.routers.statping.service=statping"
          - "traefik.http.routers.statping.tls.certresolver=cloudflare"
    networks:
      - traefik_public

networks:
  traefik_public:
    external: true