
services:
    scraper:
        image: amerkurev/scrapper:v1.0.0
        networks:
            - pricebuddy
        #ports:
        #    - 3030:3000 # Optional, if you want to access the scrapper api from the host machine
        deploy:
          placement:
            constraints: [node.role == manager]
    database:
        image: mariadb:12.0.2-noble
        environment:
            MARIADB_DATABASE: pricebuddy
            MARIADB_USER: pricebuddy
            MARIADB_PASSWORD: ${DB_PASSWORD} 
            MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD} 
        volumes:
            - /srv/containers/pricebuddy/db:/var/lib/mysql
        networks:
            - pricebuddy

        deploy:
          placement:
            constraints: [node.role == manager]

    pricebuddy:
        image: jez500/pricebuddy:v1.0.39
        #ports:
        #    - 8080:80
        volumes:
            - /srv/containers/pricebuddy/storage:/app/storage
            - /srv/containers/pricebuddy/storage/.env:/app/.env
        environment:
            DB_HOST: tasks.pricebuddy_database                     # Name of the database service
            DB_USERNAME: pricebuddy                 # Should match the MYSQL_USER in the database service
            DB_PASSWORD: ${DB_PASSWORD}                 # Should match the MYSQL_PASSWORD in the database service
            DB_DATABASE: pricebuddy                 # Should match the MYSQL_DATABASE in the database service
            APP_USER_EMAIL: admin@example.com       # Only used for seeding the database
            APP_USER_PASSWORD: admin                # Only used for seeding the database
            SCRAPER_BASE_URL: http://tasks.pricebuddy_scraper:3000   # Url to Name of the scrapper service
            AFFILIATE_ENABLED: "true"                 # See https://pricebuddy.jez.me/support-project.html
            APP_DEBUG: "true"
            APP_ENV: "local"
        deploy:
          placement:
            constraints: [node.role == manager]
          labels:
            - "traefik.enable=true"
            - "traefik.http.routers.pricebuddy.rule=Host(\"${FQDN}\")" #Define in POrtainer
            - "traefik.http.routers.pricebuddy.entrypoints=websecure"
            - "traefik.http.services.pricebuddy.loadbalancer.server.port=80"
            - "traefik.http.routers.pricebuddy.service=pricebuddy"
            - "traefik.http.routers.pricebuddy.tls.certresolver=cloudflare"
        networks:
            - pricebuddy
            - traefik_public


networks:
  traefik_public:
    external: true
  pricebuddy:
    driver: overlay
    name: pricebuddy