version: "3.5"
services:
  postgres:
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} #Define in Portainer
    image: postgres:17.4-bookworm
    volumes:
      - /srv/containers/linkwarden/pgdata:/var/lib/postgresql/data
    networks:
      - linkwarden
    deploy:
      placement:
        constraints: [node.role == manager]
  linkwarden:
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@tasks.linkwarden_postgres:5432/postgres
      - NEXTAUTH_URL=https://${FQDN}/api/v1/auth
      - NEXTAUTH_SECRET=${POSTGRES_PASSWORD} # Same as abobe
    image: ghcr.io/linkwarden/linkwarden:v2.13.0 # comment this line to build from source
    #ports:
    #  - target: 3000
    #    published: 3000
    #    mode: host
    volumes:
      - /srv/containers/linkwarden/data:/data/data
    deploy:
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.linkwarden.rule=Host(\"${FQDN}\")" #Define in POrtainer
        - "traefik.http.routers.linkwarden.entrypoints=websecure"
        - "traefik.http.services.linkwarden.loadbalancer.server.port=3000"
        - "traefik.http.routers.linkwarden.service=linkwarden"
        - "traefik.http.routers.linkwarden.tls.certresolver=cloudflare"
    networks:
      - traefik_public
      - linkwarden
networks:
  traefik_public:
    external: true
  linkwarden:
    driver: overlay
    name: linkwarden
