services:
  postgres:
    image: postgres:17.4-bookworm
    #user: 65534:65534
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: vikunja
      PGDATA: /var/lib/postgresql/data/vikunja
    volumes:
      - /srv/containers/vikunja/pgdata:/var/lib/postgresql/data
    networks:
      - vikunja
    deploy:
      placement:
        constraints: [node.role == manager]
  vikunja:
    image: vikunja/vikunja:0.24.6
    environment:
      VIKUNJA_SERVICE_PUBLICURL: https://vikunja.gleiton.info
      VIKUNJA_DATABASE_HOST: tasks.vikunja_postgres
      VIKUNJA_DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      VIKUNJA_DATABASE_TYPE: postgres
      VIKUNJA_DATABASE_USER: vikunja
      VIKUNJA_DATABASE_DATABASE: vikunja
      VIKUNJA_SERVICE_JWTSECRET: ${JWTSECRET}
    volumes:
      - /srv/containers/vikunja/data:/app/vikunja/files
    ports:
      - 3456:3456
    networks:
      - traefik_public
      - vikunja
    deploy:
      placement:
        constraints: [node.hostname == lxc-docker-01]
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.vikunja.rule=Host(`vikunja.gleiton.info`)"
        - "traefik.http.routers.vikunja.entrypoints=websecure"
        - "traefik.http.services.vikunja.loadbalancer.server.port=3456"
        - "traefik.http.routers.vikunja.service=vikunja"
        - "traefik.http.routers.vikunja.tls.certresolver=cloudflare"
networks:
  traefik_public:
    external: true
  vikunja:
    driver: overlay
    name: vikunja
