services:
  glance:
    container_name: glance
    image: glanceapp/glance:v0.7.10
    volumes:
      - /srv/containers/glance/config:/app/config
      - /srv/containers/glance/assets:/app/assets
      # Optionally, also mount docker socket if you want to use the docker containers widget
      # - /var/run/docker.sock:/var/run/docker.sock:ro
    #ports:
    #  - 8080:8080
    deploy:
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.glance.rule=Host(\"${FQDN}\")" #Define in POrtainer
        - "traefik.http.routers.glance.entrypoints=websecure"
        - "traefik.http.services.glance.loadbalancer.server.port=8080"
        - "traefik.http.routers.glance.service=glance"
        - "traefik.http.routers.glance.tls.certresolver=cloudflare"
    networks:
        - traefik_public

networks:
  traefik_public:
    external: true
