services:
  wallos:
    image: bellamy/wallos:4.3.0
    #ports:
    #  - "8282:80/tcp"
    environment:
      TZ: 'America/Sao_Paulo'
    # Volumes store your data between container upgrades
    volumes:
      - '/srv/containers/wallos/db:/var/www/html/db'
      - '/srv/containers/wallos/logos:/var/www/html/images/uploads/logos'
    deploy:
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.wallos.rule=Host(\"${FQDN}\")" #Define in Portainer
        - "traefik.http.routers.wallos.entrypoints=websecure"
        - "traefik.http.services.wallos.loadbalancer.server.port=80"
        - "traefik.http.routers.wallos.service=wallos"
        - "traefik.http.routers.wallos.tls.certresolver=cloudflare"
    networks:
      - traefik_public
networks:
  traefik_public:
    external: true
