---
version: "3.8"
services:
  kasm:
    image: lscr.io/linuxserver/kasm:latest
    container_name: kasm
    privileged: true
    environment:
      - KASM_PORT=9443
    volumes:
      - /srv/containers/kasm/data:/opt
      - /srv/containers/kasm/profiles:/profiles #optional
      #- /dev/input:/dev/input #optional
      #- /run/udev/data:/run/udev/data #optional
    ports:
      - 3000:3000
      - 9443:9443
    restart: unless-stopped
    networks:
     # - proxy
      - kasm
    #labels:
    #  - "traefik.enable=true"
    #  - "traefik.http.routers.kasm.rule=Host(\"${FQDN}\")
    #  - "traefik.http.services.kasm.loadbalancer.server.port=9443"
    #  - "traefik.http.routers.kasm.tls.certresolver=cloudflare"
    #  - "traefik.http.services.kasm.loadbalancer.server.scheme=https" #Addded to avoid error 400 "http sent do https port"
    #  - "traefik.http.routers.kasm.service=kasm"
    #  - "traefik.docker.network=traefik_proxy"
    #  - "traefik.http.routers.kasm.entrypoints=websecure"
    #  - "traefik.http.routers.kasm.priority=1"

networks:
  kasm:
    name: kasm
    driver: bridge
  #traefik_proxy:
  #  external: true

