services:
  portainer-agent:
    image: portainer/agent:2.22.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - traefik_public
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer-ce:2.34.0
    command: -H tcp://tasks.portainer-agent:9001 --tlsskipverify
    ports:
      - 8000:8000
      - 9000:9000
      #- target: 9443
      # published: 9443
      #  mode: host
      #- target: 9000
      #  published: 9000
      #  mode: host
      #- target: 8000
      #  published: 8000
      #  mode: host
    volumes:
      - /srv/containers/portainer:/data
    networks:
      - traefik_public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        # Frontend
        - "traefik.enable=true"
        - "traefik.http.routers.portainer.rule=Host(\"${FQDN}\")"
        - "traefik.http.routers.portainer.entrypoints=websecure"
        - "traefik.http.services.portainer.loadbalancer.server.port=9000"
        - "traefik.http.routers.portainer.service=portainer"
        - "traefik.http.routers.portainer.tls.certresolver=cloudflare"
networks:
  traefik_public:
    driver: overlay
    name: traefik_public
    attachable: true