#Prometheus config file
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 60s
    static_configs:
      - targets: ['tasks.monitoring_prometheus:9090']

  - job_name: 'node_exporter'
    scrape_interval: 60s
    static_configs:
      - targets: ['tasks.monitoring_node_exporter:9100']

  - job_name: 'cadvisor'
    scrape_interval: 60s
    scrape_timeout: 10s
    static_configs:
      - targets: ['tasks.monitoring_cadvisor:8080']
