#Prometheus config file
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 60s
    static_configs:
      - targets: ['tasks.monitoring_prometheus:9090']

  - job_name: 'node_exporter'
    scrape_interval: 60s
    static_configs:
      - targets: 
        - tasks.monitoring_node_exporter:9100
        - 192.168.1.100
        - ...
    relabel_configs:
    - source_labels: [__address__]
      regex: tasks.monitoring_node_exporter:9100
      target_label: instance
      replacement: node1
    - source_labels: [__address__]
      regex: 192.168.1.100:9100
      target_label: instance
      replacement: node2


  - job_name: 'cadvisor'
    scrape_interval: 60s
    scrape_timeout: 10s
    static_configs:
      - targets: ['tasks.monitoring_cadvisor:8080']

  - job_name: 'pve'
    static_configs:
      - targets:
        - 192.168.1.2  # Proxmox VE node.
        - 192.168.1.3  # Proxmox VE node.
    metrics_path: /pve
    params:
      module: [default]
      cluster: ['1']
      node: ['1']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: tasks.monitoring_pve-exporter:9221  # PVE exporter.
