# Configuration to receive UDP/TCP syslog packets
# Make sure imudp/imtcp modules are enabled in /etc/rsyslog.conf:
# module(load="imudp")
# input(type="imudp" port="514")

# ----------------------------------------------------------------------
# Output Channels Configuration (Max Size: 10MB)
# ----------------------------------------------------------------------
$OutChannel pve1,/var/log/rsyslog/pve/pve1.log,10485760
$OutChannel pve2,/var/log/rsyslog/pve/pve2.log,10485760
$OutChannel openwrt,/var/log/rsyslog/openwrt/openwrt.log,10485760
$OutChannel omv,/var/log/rsyslog/omv/omv.log,10485760
$OutChannel docker-host,/var/log/rsyslog/vm/docker-host.log,10485760

# OPNsense Specific Channels
$OutChannel opnsense-unbound,/var/log/rsyslog/opnsense/unbound.log,10485760
$OutChannel opnsense-firewall,/var/log/rsyslog/opnsense/filterlog.log,10485760
$OutChannel opnsense-system,/var/log/rsyslog/opnsense/system.log,10485760

# ----------------------------------------------------------------------
# Filtering and Routing Rules
# ----------------------------------------------------------------------

# OPNsense Router/Firewall
if $fromhost-ip == '192.168.XXX.1' then {
    if $programname == 'unbound' then {
        :omfile:$opnsense-unbound
    } else if $programname == 'filterlog' then {
        :omfile:$opnsense-firewall
    } else {
        :omfile:$opnsense-system
    }
    stop
}

# OpenWRT
if $fromhost-ip == '192.168.XXX.2' then {
    :omfile:$falcon
    stop
}

# Proxmox PVE1
if $fromhost-ip == '192.168.XXX.XX' then {
    :omfile:$pve1
    stop
}

# VM Docker Host
if $fromhost-ip == '192.168.XXX.XX' then {
    :omfile:$docker-host
    stop
}

# Proxmox PVE2
if $fromhost-ip == '192.168.XXX.XX' then {
    :omfile:$pve2
    stop
}

# OMV
if $fromhost-ip == '192.168.XXX.XX' then {
    :omfile:omv
    stop
}
